Trunk/Prometheus.Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prometheus.BL.Interfaces;
using Prometheus.Common.Enums;
using Prometheus.Common.Extensiosns;

namespace Prometheus.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IDashboardService _dashboardService;

        public DashboardController(IDashboardService dashboardService)
        {
            _dashboardService = dashboardService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var result = _dashboardService.GetDashboardData(User.Identity.GetUserProfileId() ?? default(long));
            if (result.Status != StatusEnum.Success)
            {
                return BadRequest();
            }
            return View(result.Value);
        }
    }
}

Trunk/Prometheus.Web/Controllers/ExchangeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Prometheus.BL.Interfaces;
using Prometheus.BL.Services;
using Prometheus.Common.Enums;
using Prometheus.Model.Models.ExchangesModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Prometheus.Web.Controllers
{
    [Authorize]
    public class ExchangeController : Controller
    {
        private readonly IExchangesService _exchangesService;        

        public ExchangeController(IExchangesService exchangesService)
        {
            _exchangesService = exchangesService;            
        }
        [Route("/exchanges/overview")]
        public IActionResult Index()
        {
            var model = _exchangesService.GetAll();
            return View(model);
        }
        [Route("/exchanges/{name}")]
        public IActionResult Details(AvailableExchanges name)
        {
            var model = _exchangesService.GetDetails(name);            
            return View(model);
        }

        [Route("/exchanges/settings")]
        public IActionResult Settings()
        {
            var model = _exchangesService.GetAll();
            return View(model);
        }        

        [HttpPost]
        public JsonResult SaveSymbols(AvailableExchanges name)
        {
            var result = _exchangesService.SaveSymbolsForExchange(name);
            return Json(result);
        }

        [HttpPost]
        public JsonResult DeleteSymbols(AvailableExchanges name)
        {
            var result = _exchangesService.DeleteAllSymbolsForExchange(name);
            return Json(result);
        }

        [HttpGet]
        public IList<TickerModel> Overview(AvailableExchanges exchangeName, string market)
        {
            var result = _exchangesService.GetOverview(exchangeName, market);
            return result;
        }
    }
}

Trunk/Prometheus.Web/Controllers/MediaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Prometheus.Media;
using Prometheus.Media.SocialMedia;
using Prometheus.Model.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Prometheus.Web.Controllers
{
    [Authorize]
    public class MediaController : Controller
    {
        private readonly Lazy<IRssMedia> _rssClient;
        private readonly IFacebookService _facebookService;

        public MediaController(Lazy<IRssMedia> rssClient, IFacebookService facebookService)
        {
            _rssClient = rssClient;
            _facebookService = facebookService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetMediaReport()
        {
            return Json(_rssClient.Value.MediaReport());
            //return Json(new List<int>() { 5, 4, 15, 1, 2, 0, 0, 11 });
        }

        [HttpGet]
        public IActionResult GetSocialMediaReport()
        {
            //return Json(await _facebookService.SocialMediaReport());
            return Json(new List<int>() { 20, 15, 2, 1, 1, 12, 14, 6 });
        }
    }
}

Trunk/Prometheus.Web/Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prometheus.BL.Interfaces;
using Prometheus.BL.Services;
using Prometheus.Common.Extensiosns;
using Prometheus.Model.Models;
using Prometheus.Model.Models.ScheduleModel;
using Prometheus.Web.SchedulerRecurrence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;


namespace Prometheus.Web.Controllers
{
    [Authorize]
    public class ScheduleController : Controller
    {
        private readonly IScheduleService _scheduleService;
        private readonly ISelectListService _selectList;

        public ScheduleController(IScheduleService scheduleService, ISelectListService selectList)
        {
            _scheduleService = scheduleService;
            _selectList = selectList;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Get(string startDate, string endDate)
        {
            var start = DateTime.Parse(startDate);
            var end = DateTime.Parse(endDate);
            var result = _scheduleService.GetSchedule((User.Identity.GetUserProfileId() ?? default(long)), start, end);
            if (result.Status == Common.Enums.StatusEnum.Success)
            {
                return Json(result.Value);
            }
            else
            {
                return Json(result.Message);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            var userProfileId = User.Identity.GetUserProfileId();
            var model = new ScheduleModel
            {
                JobDefinitions = _selectList.GetList<JobDefinitionSelectListModel>(userProfileId ?? default(long))
            };

            return PartialView("_CreatePartial", model);
        }

        [HttpPost]
        public IActionResult Post(ScheduleModel model)
        {
            model.UserProfileId = User.Identity.GetUserProfileId() ?? default(long);

            if (ModelState.IsValid)
            {
                var dates = model.RecurrenceRule != null ? RecurrenceHelper.GetRecurrenceDateTimeCollection(model.RecurrenceRule, model.StartDate) : null;
                var result = _scheduleService.CreateSchedule(model, dates);

                return Json(result);
            }
            
            return PartialView("_CreatePartial", model);
        }


        [HttpGet]
        public IActionResult GetScheduleById(long scheduleId, long jobId)
        {
            var userProfileId = User.Identity.GetUserProfileId();
            var result = _scheduleService.GetScheduleById(scheduleId, jobId);

            if(result.Status == Common.Enums.StatusEnum.Success)
            {
                result.Value.JobDefinitions = _selectList.GetList<JobDefinitionSelectListModel>(userProfileId ?? default(long));
            }
            var model = result.Value;
            return PartialView("_EditPartial", model);
           
        }

        [HttpPost]
        public IActionResult Put(ScheduleModel model)
        {
            model.UserProfileId = User.Identity.GetUserProfileId() ?? default(long);
            if (ModelState.IsValid)
            {
                var dates = model.RecurrenceRule != null ? RecurrenceHelper.GetRecurrenceDateTimeCollection(model.RecurrenceRule, model.StartDate) : null;
                var result = _scheduleService.EditSchedule(model, dates);
                
                return Json(result);
            }
            return PartialView("_EditPartial", model);
        }

        [HttpPost]
        public IActionResult DeleteSchedule(long id)
        {
            var result = _scheduleService.DeleteSchedule(id);
            return Json(result.Message);
        }

        [HttpPost]
        public IActionResult DeleteJob(long id)
        {
            var result = _scheduleService.DeleteJob(id);
            return Json(result);
        }
    }
}

Trunk/Prometheus.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Prometheus</title>
    <meta name="description" content="Prometheus">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/assets/css/normalize.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/assets/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="~/assets/scss/style.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

    <script src="~/assets/js/vendor/jquery-2.1.4.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>*@
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/main.js"></script>

    @RenderSection("Styles", required: false)

</head>
<body>

    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" asp-controller="Dashboard" asp-action="Index"><span>Prometheus</span></a>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div id="main-menu" class="main-menu collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <h3 class="menu-title">Adapters</h3><!-- /.menu-title -->
                        <li id="enterprise" class="menu-item-has-children dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-database"></i>Enterprise</a>
                            <ul class="sub-menu children dropdown-menu">
                                <li><i class="menu-icon fa fa-cogs"></i><a asp-controller="EnterpriseAdapter" asp-action="Index">Adapter settings</a></li>
                            </ul>
                        </li>
                        <li id="crypto" class="menu-item-has-children dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-btc"></i>Crypto</a>
                            <ul class="sub-menu children dropdown-menu">
                                <li><i class="menu-icon fa fa-cogs"></i><a asp-controller="CryptoAdapter" asp-action="Index">Adapter settings</a></li>
                            </ul>
                        </li>
                        <li id="business" class="menu-item-has-children dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-line-chart"></i>Business</a>
                            <ul class="sub-menu children dropdown-menu">
                                <li><i class="menu-icon fa fa-cogs"></i><a asp-controller="BusinessAdapter" asp-action="Index">Adapter settings</a></li>
                            </ul>
                        </li>

                        <h3 class="menu-title">Jobs</h3><!-- /.menu-title -->
                        <li id="definition" class="menu-item dropdown">
                            <a asp-controller="JobDefinition" asp-action="Index"> <i class="menu-icon fa fa-briefcase"></i>Definition</a>
                        </li>
                        <li id="history" class="menu-item dropdown">
                            <a asp-controller="JobHistory" asp-action="Index"> <i class="menu-icon fa fa-history"></i>History</a>
                        </li>

                        <h3 class="menu-title">Calendar</h3><!-- /.menu-title -->
                        <li id="schedule" class="menu-item dropdown">
                            <a asp-controller="Schedule" asp-action="Index"> <i class="menu-icon fa fa-calendar"></i>Schedule</a>
                        </li>
                        <li id="timeline" class="menu-item dropdown">
                            <a asp-controller="JobTimeline" asp-action="Index"> <i class="menu-icon fa fa-list"></i>Timeline</a>
                        </li>

                        <h3 class="menu-title">Outlet</h3><!-- /.menu-title -->
                        <li id="exchanges" class="menu-item-has-children dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-exchange"></i>Exchanges</a>
                            <ul class="sub-menu children dropdown-menu">
                                <li><i class="fa fa-list"></i><a asp-controller="Exchange" asp-action="Index">Overview</a></li>
                                <li><i class="fa fa-cogs"></i><a asp-controller="Exchange" asp-action="Settings">Settings</a></li>
                            </ul>
                        </li>

                        <li id="media" class="menu-item dropdown">
                            <a asp-controller="Media" asp-action="Index"> <i class="menu-icon fa fa-globe"></i>Media</a>

                        </li>

                    </ul>
                </div><!-- /.navbar-collapse -->
            }
        </nav>
    </aside><!-- /#left-panel -->
    <!-- Left Panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">
            <div class="header-menu">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="col-sm-7">
                        <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                        <div class="header-left">
                            <button class="search-trigger"><i class="fa fa-search"></i></button>
                            <div class="form-inline">
                                <form class="search-form">
                                    <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                                    <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                                </form>
                            </div>
                            @await Html.PartialAsync("~/Views/Notification/Default.cshtml")
                        </div>
                    </div>

                    <div class="col-sm-5">

                        <div class="user-area dropdown float-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-caret-down fa-lg" style="color:#272c33"></i>
                                <span>@User.Identity.FirstName()</span>
                            </a>
                            <div class="user-menu dropdown-menu">
                                <a class="nav-link" href="#"><i class="fa fa-user"></i> My Profile</a>
                                <a class="nav-link" href="#"><i class="fa fa-cog"></i> Settings</a>
                                <a asp-controller="Account" asp-action="Logout" class="nav-link"><i class="fa fa-power-off"></i> Logout</a>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-sm-7">
                        <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    </div>
                    <div class="col-sm-5">
                        <div class="user-area dropdown float-right">
                            <a asp-controller="Account" asp-action="Register" style="padding-right:2em"> <i class="fa fa-user-plus"></i> Register</a>
                            <a asp-controller="Account" asp-action="Login"> <i class="fa fa-sign-in"></i> Login</a>

                        </div>
                    </div>
                }
            </div>
        </header><!-- /header -->
        <!-- Header-->
        @if (User.Identity.IsAuthenticated)
        {
            <div class="breadcrumbs">
                <div class="col-sm-8">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <ol class="breadcrumb text-left">
                                @if (ViewContext.RouteData.Values["controller"].ToString() == "Dashboard")
                                {
                                    <li>
                                        <i class="ti-home">
                                        </i>
                                        @Html.ActionLink("Home", "Index", "Dashboard")
                                    </li>
                                }

                                @if (ViewContext.RouteData.Values["controller"].ToString() != "Dashboard")
                                {
                                    <li>
                                        <i class="ti-home"></i>
                                        @Html.ActionLink("Home", "Index", "Dashboard")
                                    </li>
                                    <li class="active">
                                        @Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index")
                                    </li>
                                    if (ViewContext.RouteData.Values["action"].ToString() != "Index")
                                    {
                                        <li class="active">
                                            @Html.Label(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString())
                                        </li>
                                    }
                                }

                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="content mt-3">
            @RenderBody()
        </div>

    </div><!-- /#right-panel -->
    <!-- Right Panel -->


    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/js/bootstrap.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>*@
        <script src="~/js/site.js"> type = "text/javascript"</script>
        <script src="~/js/bootbox.js"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>*@
        <script src="~/js/site.min.js"> type = "text/javascript"</script>
        <script src="~/js/bootbox.min.js"></script>
    </environment>


    @RenderSection("Scripts", required: false)

</body>
</html>

<script>
    handleSideBarListItem();
</script>