Trunk/Prometheus.Web/Controllers/BusinessAdapterController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prometheus.BL.Interfaces;
using Prometheus.Common.Enums;
using Prometheus.Common.Extensiosns;
using Prometheus.Model.Models;

namespace Prometheus.Web.Controllers
{
    [Authorize]
    public class BusinessAdapterController : Controller
    {
        private readonly IBusinessAdapterService _businessAdapterService;

        public BusinessAdapterController(IBusinessAdapterService businessAdapterService)
        {
            _businessAdapterService = businessAdapterService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var result = _businessAdapterService.GetBusinessAdapters(User.Identity.GetUserProfileId() ?? default(long));

            if (result.Status != StatusEnum.Success)
            {
                return BadRequest();
            }

            return View(result.Value);
        }

        [HttpGet]
        public IActionResult Create()
        {
            //var model = _businessAdapterService.GetInitModel();

            return PartialView("_CreatePartial"/*, model*/);
        }

        [HttpPost]
        public IActionResult Create(BusinessAdapterModel model)
        {
            var userProfileId = User.Identity.GetUserProfileId();

            if (ModelState.IsValid)
            {
                var response = _businessAdapterService.CreateBusinessAdapter(model, (long)userProfileId);
                return Json(response);
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(long Id)
        {
            var response = _businessAdapterService.GetBusinessAdapter(Id);

            if (response.Status == StatusEnum.Error)
            {
                return BadRequest();
            }

            var model = response.Value;

            return PartialView("_EditPartial", model);
        }

        [HttpPost]
        public IActionResult Edit(BusinessAdapterModel model)
        {
            if (ModelState.IsValid)
            {
                var response = _businessAdapterService.UpdateBusinessAdapter(model);
                return Json(response);
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(long businessAdapterId)
        {
            var response = _businessAdapterService.DeleteBusinessAdapter(businessAdapterId);

            return Json(response);
        }


        [HttpGet]
        public IActionResult Details(long? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var result = _businessAdapterService.GetBusinessAdapter(Convert.ToInt64(Id));
            var model = result.Value;

            return PartialView("_DetailsPartial", model);
        }
    }
}

Trunk/Prometheus.Web/Views/BusinessAdapter/Index.cshtml
@model IEnumerable<BusinessAdapterModel>
@{
    int counter = 0;
}

@section Styles{

    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
}

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Business Adapter</strong>
                        &nbsp;
                        <a href="#" onclick="createBusinessAdapter()" title="Add business adapter">
                            <i class="fa fa-plus-square fa-lg"></i>
                        </a>
                    </div>
                    <div class="card-body">
                        <div style="overflow-x:auto;">

                            <table id="BusinessAdapterTable" class="table table-striped table-bordered">
                                <thead>
                                    <tr role="row">
                                        <th style="text-align:center">#</th>
                                        <th>Name</th>
                                        <th>Adapter Type</th>
                                        <th>Direction</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr role="row" class="odd">
                                            <td class="sorting_1" style="text-align:center">@(counter += 1)</td>
                                            <td>
                                                <a href="#" onclick="businessAdapterDetails(@item.Id)" title="Details">
                                                    @item.Name
                                                </a>
                                            </td>

                                            <td>@item.BusinessAdapterType</td>
                                            <td>@item.Direction.ToString()</td>
                                            <td>
                                                <a href="#" onclick="businessAdapterDetails(@item.Id)" title="Details">
                                                    <i class="fa fa-info-circle fa-lg"></i>
                                                </a>
                                                &nbsp;
                                                <a href="#" onclick="editBusinessAdapter(@item.Id)" title="Edit">
                                                    <i class="fa fa-pencil fa-lg"></i>
                                                </a>
                                                &nbsp;
                                                <a href="#" onclick="confirmDelete(@item.Id)" title="Delete">
                                                    <i class="fa fa-trash fa-lg"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

<div class="modal fade" id="createBusinessAdapterModal" tabindex="-1" role="dialog" aria-labelledby="createBusinessAdapterModal" aria-hidden="true" data-backdrop="static">
    <div id="createBusinessAdapterContainer">
    </div>
</div>

<div class="modal fade" id="editBusinessAdapterModal" tabindex="-1" role="dialog" aria-labelledby="editBusinessAdapterModal" aria-hidden="true" data-backdrop="static">
    <div id="editBusinessAdapterContainer">
    </div>
</div>

<div class="modal fade" id="businessAdapterDetailsModal" tabindex="-1" role="dialog" aria-labelledby="businessAdapterDetailsModal" aria-hidden="true" data-backdrop="static">
    <div id="businessAdapterDetailsContainer">
    </div>
</div>


@section Scripts{

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

    <script>

        //create
        function createBusinessAdapter () {

            jQuery.get('@Url.Action("Create", "BusinessAdapter")', function (model) {
                jQuery('#createBusinessAdapterContainer').html(model);
                jQuery('#createBusinessAdapterModal').modal("show");
            })
        }

        function createValidation() {

            jQuery("#connection").text("");

            var valid = jQuery("#form").valid();

            if (!valid) {
                return;
            }
            else {
                var model = {
                    Direction: jQuery("input[name = 'direction']:checked").val(),
                    Name: jQuery("#Name").val(),
                    BusinessAdapterType: jQuery("#BusinessAdapterType").val(),
                    FileName: jQuery("#FileName").val()
                };

                jQuery.ajax({
                    url: '@Url.Action("Create", "BusinessAdapter")',
                    datatype: 'json',
                    type: 'post',
                    data: model,
                    success: function (response) {

                        if (response.status == 0) {
                            jQuery('#createBusinessAdapterModal').modal('hide');
                            jQuery('#createBusinessAdapterContainer').html("");
                            bootbox.alert(response.message, function () {
                                window.location.replace('@Url.Action("Index", "BusinessAdapter")');
                            })
                        }
                        else {
                            jQuery("#connection").text(response.message);
                        }
                    },
                    error: function () {
                        bootbox.alert("Something went wrong. Please try again.");
                    }
                })
            }
        }

        //edit
        function editBusinessAdapter(Id) {

            jQuery.ajax({
                type: "GET",
                url: '@Url.Action("Edit", "BusinessAdapter")',
                data: { Id: Id },
                success: function (model) {

                    jQuery('#editBusinessAdapterContainer').html(model);
                    jQuery('#editBusinessAdapterModal').modal("show");
                }
            })
        }

        function editValidation() {
            var valid = jQuery("#formEditBusinessAdapter").valid();

            if (!valid) {
                return;
            }

            else {

                var model = {
                    Id: jQuery("#Id").val(),
                    Direction: jQuery("input[name = 'direction']:checked").val(),
                    Name: jQuery("#Name").val(),
                    BusinessAdapterType: jQuery("#BusinessAdapterType").val(),
                    FileName: jQuery("#FileName").val()
                }


                jQuery.ajax({
                    url: '@Url.Action("Edit", "BusinessAdapter")',
                    datatype: 'json',
                    type: 'post',
                    data: model,
                    success: function (response) {
                        if (response.status == 0) {
                            jQuery('#editBusinessAdapterModal').modal('hide');
                            jQuery('#editBusinessAdapterContainer').html("");
                            bootbox.alert(response.message, function () {
                                window.location.replace('@Url.Action("Index", "BusinessAdapter")');
                            })
                        }
                        else {
                            jQuery("#connection").text(response.message);
                        }
                    },
                    error: function () {
                        bootbox.alert("Something went wrong. Please try again.");
                    }
                })
            }
        }

        //details
        function businessAdapterDetails(Id) {

            jQuery.ajax({
                type: "GET",
                url: '@Url.Action("Details", "BusinessAdapter")',
                data: { Id: Id },
                success: function (model) {

                    jQuery('#businessAdapterDetailsContainer').html(model);
                    jQuery('#businessAdapterDetailsModal').modal("show");
                }
            })
        }

        //delete
        function confirmDelete(busAdapterId) {

            var confirmedBootbox = bootbox.confirm("Are you sure you want to delete this business adapter?", function (result) {
                if (result) {
                    var id = busAdapterId;

                    jQuery.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "BusinessAdapter")',
                        data: { businessAdapterId: id },
                        dataType: 'json',
                        success: function (response) {

                            if (response.message != null) {
                                bootbox.alert(response.message);
                            } else {
                                window.location.replace('@Url.Action("Index", "BusinessAdapter")');
                            }
                        },
                        error: function () {
                            bootbox.alert("Something went wrong. Please try again later.")
                        }
                    })
                }
            })
        }

        //data tables
        jQuery(document).ready(function () {
            jQuery("#BusinessAdapterTable").dataTable({
                "ordering": false
            })
        })

    </script>
}

Trunk/Prometheus.Web/Views/BusinessAdapter/_CreatePartial.cshtml
@model BusinessAdapterModel

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Add Business Adapter</h4>
            <button type="button" class="close" onclick="closeCreateBusinessAdapterModal()">&times;</button>
        </div>

        <div class="modal-body">

            <form class="form-horizontal" id="form">
                <div class="card-body card-block">

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="Direction" class="form-control-label">Direction</label>
                        </div>
                        <div class="col-12 col-md-8" id="directionRadioBtn">
                            <input type="radio" name="direction" value="1" disabled>&nbsp;Source &nbsp;&nbsp;
                            <input type="radio" name="direction" value="2" checked>&nbsp;Destination
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="NodeType" class="form-control-label">Adapter type</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <select asp-for="BusinessAdapterType" asp-items="Html.GetEnumSelectList<BusinessAdapterType>()" class="form-control col-md-12"></select>
                            <span asp-validation-for="BusinessAdapterType" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="text-input" class="form-control-label">Name</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <input type="text" id="Name" asp-for="Name" name="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label asp-for="FileName" class="form-control-label"></label>
                        </div>
                        <div class="col-12 col-md-8">
                            <input type="text" id="FileName" asp-for="FileName" name="Name" class="form-control">
                            <span asp-validation-for="FileName" class="text-danger"></span>
                        </div>
                    </div>


                </div>

                <div id="connection" class="text-danger mt-2"></div>
            </form>
        </div>

        <div class="modal-footer">
            <div class="form-group col-md-12">

                <button type="button" class="btn btn-primary btn-sm mr-1" onclick="createValidation()">
                    <i class="fa fa-dot-circle-o"></i> Submit
                </button>
                <button type="button" class="btn btn-primary btn-sm" onclick="closeCreateBusinessAdapterModal()">Close</button>

            </div>
        </div>
    </div>
</div>


@await Html.PartialAsync("_ValidationScriptsPartial");

<script>
    
    function closeCreateBusinessAdapterModal() {
        jQuery("#createBusinessAdapterModal").modal("hide");
        jQuery("#createBusinessAdapterContainer").html("");
    }
</script>

Trunk/Prometheus.Web/Views/BusinessAdapter/_DetailsPartial.cshtml
@model BusinessAdapterModel

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Business Adapter Details</h4>
            <button type="button" class="close" onclick="closeBusinessAdapterModal()">&times;</button>
        </div>

        <div class="modal-body">
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Direction)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Direction)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.BusinessAdapterType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.BusinessAdapterType)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FileName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FileName)
                </dd>


            </dl>

        </div>
        <div class="modal-footer">
            <div class="form-group col-md-12">
                <button type="button" class="btn btn-primary btn-sm" onclick="editBusinessAdapterFromDetails(@Model.Id)" title="Edit business adapter">
                    <i class="fa fa-edit fa-lg"></i> Edit
                </button>
                <button type="button" class="btn btn-primary btn-sm" onclick="closeBusinessAdapterModal()">Close</button>
            </div>
        </div>
    </div>
</div>

<script>

    function closeBusinessAdapterModal() {
        jQuery("#businessAdapterDetailsModal").modal("hide");
        jQuery("#businessAdapterDetailsContainer").html("");
    }

    //body class="modal-open" dissapear after closing businessAdapterDetailsModal (refactor!)
    function editBusinessAdapterFromDetails(Id) {
        closeBusinessAdapterModal();
        editBusinessAdapter(Id);

    }

</script>

Trunk/Prometheus.Web/Views/BusinessAdapter/_EditPartial.cshtml
@model BusinessAdapterModel

<div id="modalEdit" class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Edit Business Adapter</h4>
            <button type="button" class="close" onclick="closeEditBusinessAdapterModal()">&times;</button>
        </div>

        <div class="modal-body">
            <form method="post" class="form-horizontal" id="formEditBusinessAdapter">
                <div class="card-body card-block">

                    <input asp-for="Id" type="hidden" />

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="Direction" class="form-control-label">Direction</label>
                        </div>
                        <div class="col-12 col-md-8" id="directionRadioBtn">
                            <input type="radio" name="direction" value="1" id="source" disabled>&nbsp;Source &nbsp;&nbsp;
                            <input type="radio" name="direction" value="2" id="destination" checked>&nbsp;Destination
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="NodeType" class="form-control-label">Adapter type</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <select asp-for="BusinessAdapterType" asp-items="Html.GetEnumSelectList<BusinessAdapterType>()" class="form-control col-md-12" disabled></select>
                            <span asp-validation-for="BusinessAdapterType" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="text-input" class=" form-control-label">Name</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <input type="text" id="Name" asp-for="Name" name="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label asp-for="FileName" class="form-control-label"></label>
                        </div>
                        <div class="col-12 col-md-8">
                            <input type="text" id="FileName" asp-for="FileName" name="FileName" class="form-control">
                            <span asp-validation-for="FileName" class="text-danger"></span>
                        </div>
                    </div>

                    <div id="connection" class="text-danger mt-2"></div>

                </div>
            </form>
        </div>

        <div class="modal-footer">
            <div class="form-group col-md-12">

                <button type="button" class="btn btn-primary btn-sm mr-1" onclick="editValidation()">
                    <i class="fa fa-dot-circle-o"></i> Submit
                </button>
                <button type="button" class="btn btn-primary btn-sm" onclick="closeEditBusinessAdapterModal()">Close</button>

            </div>
        </div>
    </div>
</div>


@await Html.PartialAsync("_ValidationScriptsPartial");

<script>
    function closeEditBusinessAdapterModal() {
        jQuery("#editBusinessAdapterModal").modal("hide");
        jQuery("#editBusinessAdapterContainer").html("");

    }
</script>