Trunk/Prometheus.Web/Controllers/CryptoAdapterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Prometheus.BL.Interfaces;
using Prometheus.Common.Extensiosns;
using Prometheus.BL.Services;
using Prometheus.Model.Models;
using Microsoft.AspNetCore.Authorization;
using Prometheus.Common.Enums;

namespace Prometheus.Web.Controllers
{
    [Authorize]
    public class CryptoAdapterController : Controller
    {

        private readonly ICryptoAdapterService _cryptoAdapterService;

        public CryptoAdapterController(ICryptoAdapterService cryptoAdapterService)
        {
            _cryptoAdapterService = cryptoAdapterService;
        }

        public IActionResult Index()
        {
            var result = _cryptoAdapterService.GetCryptoAdapters(User.Identity.GetUserProfileId() ?? default(long));

            if (result.Status != Common.Enums.StatusEnum.Success)
            {
                return BadRequest();
            }

            return View(result.Value);
        }

        public IActionResult Create()
        {
            var model = _cryptoAdapterService.GetInitModel();

            return PartialView("_CreatePartial", model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CryptoAdapterModel model)
        {
            var userProfileId = User.Identity.GetUserProfileId();

            if (ModelState.IsValid)
            {
                var response = await _cryptoAdapterService.CreateCryptoAdapter(model, (long)userProfileId);
                return Json(response);
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(long Id)
        {
            var response = _cryptoAdapterService.GetCryptoAdapter(Id);

            if (response.Status == StatusEnum.Error)
            {
                return BadRequest();
            }

            return PartialView("_EditPartial", response.Value);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CryptoAdapterModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _cryptoAdapterService.UpdateCryptoAdapter(model);
                return Json(response);
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(long cryptoAdapterId)
        {
            var response = _cryptoAdapterService.DeleteCryptoAdapter(cryptoAdapterId);
            
            return Json(response);
        }


        [HttpGet]
        public IActionResult Details(long Id)
        {
            var response = _cryptoAdapterService.GetCryptoAdapter(Id);

            if (response.Status == StatusEnum.Error)
            {
                return BadRequest();
            }

            return PartialView("_DetailsPartial", response.Value);
        }
    }
}

Trunk/Prometheus.Web/Views/CryptoAdapter/Index.cshtml
@model IEnumerable<CryptoAdapterModel>
@{
    int counter = 0;
}

@section Styles{

    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
}

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Crypto Adapter</strong>
                        &nbsp;
                        <a href="#" onclick="createCryptoAdapter()" title="Add crypto adapter">
                            <i class="fa fa-plus-square fa-lg"></i>
                        </a>
                    </div>
                    <div class="card-body">
                        <div style="overflow-x:auto;">
                            <table id="CryptoAdapterTable" class="table table-striped table-bordered">
                                <thead>
                                    <tr role="row">
                                        <th style="text-align:center">#</th>
                                        <th>Name</th>
                                        <th>Adapter Type</th>
                                        <th>Direction</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr role="row" class="odd">
                                            <td class="sorting_1" style="text-align:center">@(counter += 1)</td>
                                            <td>
                                                <a href="#" onclick="cryptoAdapterDetails(@item.Id)" title="Details">
                                                    @item.Name
                                                </a>
                                            </td>

                                            <td>@item.NodeType</td>
                                            <td>@item.Direction.ToString()</td>
                                            <td>
                                                <a href="#" onclick="cryptoAdapterDetails(@item.Id)" title="Details">
                                                    <i class="fa fa-info-circle fa-lg"></i>
                                                </a>
                                                &nbsp;
                                                <a href="#" onclick="editCryptoAdapter(@item.Id)" title="Edit">
                                                    <i class="fa fa-pencil fa-lg"></i>
                                                </a>
                                                &nbsp;
                                                <a href="#" onclick="confirmDelete(@item.Id)" title="Delete">
                                                    <i class="fa fa-trash fa-lg"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

<div class="modal fade" id="createCryptoAdapterModal" tabindex="-1" role="dialog" aria-labelledby="createCryptoAdapterModal" aria-hidden="true" data-backdrop="static">
    <div id="createCryptoAdapterContainer">
    </div>
</div>

<div class="modal fade" id="editCryptoAdapterModal" tabindex="-1" role="dialog" aria-labelledby="editCryptoAdapterModal" aria-hidden="true" data-backdrop="static">
    <div id="editCryptoAdapterContainer">
    </div>
</div>

<div class="modal fade" id="cryptoAdapterDetailsModal" tabindex="-1" role="dialog" aria-labelledby="cryptoAdapterDetailsModal" aria-hidden="true" data-backdrop="static">
    <div id="cryptoAdapterDetailsContainer">
    </div>
</div>


@section Scripts{

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

    <script>

        //create
        function createCryptoAdapter() {

            jQuery.get('@Url.Action("Create", "CryptoAdapter")', function (data) {
                jQuery('#createCryptoAdapterContainer').html(data);
                jQuery('#createCryptoAdapterModal').modal("show");
            })
        }

        function createValidation() {

            jQuery("#connection").text("");

            var valid = jQuery("#form").valid();

            if (!valid) {
                return;
            }
            else {
                var model = {
                    Direction: jQuery("input[name = 'direction']:checked").val(),
                    Name: jQuery("#Name").val(),
                    RpcAddr: jQuery("#RpcAddr").val(),
                    RpcPort: jQuery("#RpcPort").val(),
                    NodeType: jQuery("#NodeType").val(),
                    Properties : []
                };

                jQuery(':button[type="button"]').prop('disabled', true);
                jQuery("#form :input").prop("disabled", true);
                jQuery('#loader').show();

                //var nodeType = jQuery("#NodeType").val();

                //var direction = jQuery("input[name = 'direction']:checked").val();

                console.log("NodeType: ", nodeType);
                console.log("Direction: ", direction);

                var prop = jQuery.grep(properties, function (obj) { return obj.nodeType == nodeType; })[0];

                switch (direction) {
                    case "1":
                        for (var item = 0; item < prop.sourceProperties.length; item++) {
                            prop.sourceProperties[item].value = jQuery("#" + prop.sourceProperties[item].name).val();
                        }
                        break;
                    case "2":
                        for (var item = 0; item < prop.destinationProperties.length; item++) {
                            prop.destinationProperties[item].value = jQuery("#" + prop.destinationProperties[item].name).val();
                        }
                        break;
                }

                model.Properties.push(prop);

                jQuery.ajax({
                    url: '@Url.Action("Create", "CryptoAdapter")',
                    datatype: 'json',
                    type: 'post',
                    data: model,
                    success: function (response) {

                        if (response.status == 0) {
                            jQuery('#createCryptoAdapterModal').modal('hide');
                            jQuery('#createCryptoAdapterContainer').html("");
                            bootbox.alert(response.message, function () {
                                window.location.replace('@Url.Action("Index", "CryptoAdapter")');
                        })
                        }
                        else {
                            jQuery("#connection").text(response.message);
                        }

                    },
                    error: function () {
                        bootbox.alert("Something went wrong. Please try again.");
                    },
                    complete: function () {
                        jQuery(':button[type="button"]').prop('disabled', false);
                        jQuery("#form :input").prop("disabled", false);
                        jQuery('#loader').hide();
                    }
                })
            }
        }

        //edit
        function editCryptoAdapter(Id) {

            jQuery.ajax({
                type: "GET",
                url: '@Url.Action("Edit", "CryptoAdapter")',
                data: { Id: Id },
                success: function (model) {

                    jQuery('#editCryptoAdapterContainer').html(model);
                    jQuery('#editCryptoAdapterModal').modal("show");

                }
            })
        }

        function editValidation() {
            var valid = jQuery("#formEditCryptoAdapter").valid();

            if (!valid) {
                return;
            }

            else {

                var model = {
                    Id: jQuery("#Id").val(),
                    Direction: jQuery("input[name = 'direction']:checked").val(),
                    Name: jQuery("#Name").val(),
                    RpcAddr: jQuery("#RpcAddr").val(),
                    RpcPort: jQuery("#RpcPort").val(),
                    NodeType: jQuery("#NodeType").val(),
                    Properties: []
                }
                jQuery(':button[type="button"]').prop('disabled', true);
                jQuery("#form :input").prop("disabled", true);
                jQuery('#loader').show();

                switch (direction) {
                    case "1":
                        for (var item = 0; item < prop.sourceProperties.length; item++) {
                            prop.sourceProperties[item].value = jQuery("#" + prop.sourceProperties[item].name).val();
                        }
                        break;
                    case "2":
                        for (var item = 0; item < prop.destinationProperties.length; item++) {
                            prop.destinationProperties[item].value = jQuery("#" + prop.destinationProperties[item].name).val();
                        }
                        break;
                }

                model.Properties.push(prop);

                jQuery.ajax({
                    url: '@Url.Action("Edit", "CryptoAdapter")',
                    datatype: 'json',
                    type: 'post',
                    data: model,
                    success: function (response) {
                        if (response.status == 0) {
                            jQuery('#editCryptoAdapterModal').modal('hide');
                            jQuery('#editCryptoAdapterContainer').html("");
                            bootbox.alert(response.message, function () {
                                window.location.replace('@Url.Action("Index", "CryptoAdapter")');
                            })
                        }
                        else {
                            jQuery("#connection").text(response.message);
                        }
                    },
                    error: function () {
                        bootbox.alert("Something went wrong. Please try again.");
                    },
                    complete: function () {
                        jQuery(':button[type="button"]').prop('disabled', false);
                        jQuery("#form :input").prop("disabled", false);
                        jQuery('#loader').hide();
                    }
                })
            }
        }

        //details
        function cryptoAdapterDetails(Id) {

            jQuery.ajax({
                type: "GET",
                url: '@Url.Action("Details", "CryptoAdapter")',
                data: { Id: Id },
                success: function (data) {
                    jQuery('#cryptoAdapterDetailsContainer').html(data);
                    jQuery('#cryptoAdapterDetailsModal').modal("show");
                }
            })
        }

        //delete
        function confirmDelete(cryAdapterId) {

            var confirmedBootbox = bootbox.confirm("Are you sure you want to delete this crypto adapter?", function (result) {
                if (result) {
                    var id = cryAdapterId;

                    jQuery.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "CryptoAdapter")',
                        data: { cryptoAdapterId: id },
                        dataType: 'json',
                        success: function (response) {

                            if (response.message != null) {
                                bootbox.alert(response.message);
                            } else {
                                window.location.replace('@Url.Action("Index", "CryptoAdapter")');
                            }
                        },
                        error: function () {
                            bootbox.alert("Something went wrong. Please try again later.")
                        }
                    })
                }
            })
        }

        //data tables
        jQuery(document).ready(function () {
            jQuery("#CryptoAdapterTable").dataTable({
                "ordering": false
            })
        })

    </script>
}

Trunk/Prometheus.Web/Views/CryptoAdapter/_CreatePartial.cshtml
@model CryptoAdapterModel

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Add Crypto Adapter</h4>
            <button type="button" class="close" onclick="closeCreateCryptoAdapterModal()">&times;</button>
        </div>

        <div class="modal-body">

            <form class="form-horizontal" id="form">
                <div class="card-body card-block">

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="Direction" class="form-control-label">Direction</label>
                        </div>
                        <div class="col-12 col-md-8" id="directionRadioBtn">
                            <input type="radio" name="direction" value="1" checked>&nbsp;Source &nbsp;&nbsp;
                            <input type="radio" name="direction" value="2">&nbsp;Destination
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="NodeType" class="form-control-label">Node type</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <select asp-for="NodeType" asp-items="Html.GetEnumSelectList<CryptoAdapterType>()" class="form-control col-md-12"></select>
                            <span asp-validation-for="NodeType" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-4">
                            <label for="text-input" class="form-control-label">Name</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <input type="text" id="Name" asp-for="Name" name="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row form-group" id="RpcAddrDiv">
                        <div class="col col-md-4  pr-0">
                            <label for="text-input" class="form-control-label">Rpc Address</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <input type="text" id="RpcAddr" asp-for="RpcAddr" name="RpcAddr" class="form-control">
                            <span asp-validation-for="RpcAddr" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row form-group" id="RpcPortDiv">
                        <div class="col col-md-4">
                            <label for="text-input" class="form-control-label">Rpc Port</label>
                        </div>
                        <div class="col-12 col-md-8">
                            <input type="text" id="RpcPort" asp-for="RpcPort" name="RpcPort" class="form-control">
                            <span asp-validation-for="RpcPort" class="text-danger"></span>
                        </div>
                    </div>

                    <div id="PropertySection">
                        @*@foreach (var item in Model.Properties[0].DestinationProperties)
                        {
                            <div class="row form-group">
                                <div class="col col-md-4 pr-0">
                                    <label for="text-input" class="form-control-label">@item.Name</label>
                                </div>
                                <div class="col-12 col-md-8">
                                    <input type="text" id="@(item.Name)" asp-for="@item.Name" name="@(item.Name)" class="form-control">
                                    <span asp-validation-for="@item.Name" class="text-danger"></span>
                                </div>
                            </div>
                        }*@
                    </div>


                    @*<div id="destinationDiv" class="d-none">
                        <div class="row form-group">
                            <div class="col col-md-4 pr-0">
                                <label for="text-input" class="form-control-label">Coinbase Address</label>
                            </div>
                            <div class="col-12 col-md-8">
                                <input type="text" id="Coinbase" asp-for="Coinbase" name="Coinbase" class="form-control">
                                <span asp-validation-for="Coinbase" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-4  pr-0">
                                <label for="text-input" class="form-control-label">Coinbase Password</label>
                            </div>
                            <div class="col-12 col-md-8">
                                <input type="password" id="CoinbasePassword" asp-for="CoinbasePassword" name="CoinbasePassword" class="form-control">
                                <span asp-validation-for="CoinbasePassword" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col col-md-4  pr-0">
                                <label for="text-input" class="form-control-label">New Account Password</label>
                            </div>
                            <div class="col-12 col-md-8">
                                <input type="password" id="NewAccountPassword" asp-for="NewAccountPassword" name="NewAccountPassword" class="form-control">
                                <span asp-validation-for="NewAccountPassword" class="text-danger"></span>
                            </div>

                        </div>
                    </div>*@

                    <div id="loader" class="text-secondary text-center mb-2" style="display:none"><i class="fa fa-spin fa-spinner"></i> Testing connection</div>

                    <div id="connection" class="text-danger mt-2"></div>

                </div>
            </form>
        </div>

        <div class="modal-footer">
            <div class="form-group col-md-12">

                <button type="button" class="btn btn-primary btn-sm mr-1" onclick="createValidation()">
                    <i class="fa fa-dot-circle-o"></i> Submit
                </button>
                <button type="button" class="btn btn-primary btn-sm" onclick="closeCreateCryptoAdapterModal()">Close</button>

            </div>
        </div>
    </div>
</div>


@await Html.PartialAsync("_ValidationScriptsPartial");

<script>

    var properties = @Html.Raw(Json.Serialize(Model.Properties));

    nodeType = jQuery("#NodeType").val();

    direction = jQuery("input[name = 'direction']:checked").val();

    jQuery("#NodeType").change(function () {
        nodeType = jQuery("#NodeType").val();

        jQuery("input[name = 'direction']:checked").click();
    });

    jQuery("input[name = 'direction']").click(function () {
        direction = jQuery("input[name = 'direction']:checked").val();

        generateProperties(direction);
    });

    function generateProperties(direction) {

        jQuery("#PropertySection").html("");

        var prop = jQuery.grep(properties, function (obj) { return obj.nodeType == nodeType; })[0];

        switch (direction) {
            case "1":
                for (var item = 0; item < prop.sourceProperties.length; item++) {
                    jQuery("#PropertySection").append(generateProperty(prop.sourceProperties[item].name));
                }

                break;
            case "2":
                for (var item = 0; item < prop.destinationProperties.length; item++) {
                    jQuery("#PropertySection").append(generateProperty(prop.destinationProperties[item].name));
                }
                break;
        }

    }

    function generateProperty(name) {

        var property = `
            <div class="row form-group">
                <div class="col col-md-4 pr-0">
                    <label class="form-control-label" for="text-input">${name}</label>
                </div>
                <div class="col-12 col-md-8">
                    <input name="${name}" class="form-control" id="${name}" type="text" value="">
                    <span class="text-danger field-validation-valid" data-valmsg-replace="true" data-valmsg-for="${name}"></span>
                </div>
            </div>`;

        return property;
    }

    function closeCreateCryptoAdapterModal() {
        jQuery("#createCryptoAdapterModal").modal("hide");
        jQuery("#createCryptoAdapterContainer").html("");
    }
</script>

Trunk/Prometheus.Web/Views/CryptoAdapter/_DetailsPartial.cshtml
@model CryptoAdapterModel

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Crypto Adapter Details</h4>
            <button type="button" class="close" onclick="closeCryptoAdapterModal()">&times;</button>
        </div>

        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.NodeType)
                </dt>

                <dd id="nodeType">
                    @Html.DisplayFor(model => model.NodeType)
                </dd>

                <dt id="rpcAddress">
                    @Html.DisplayNameFor(model => model.RpcAddr)
                </dt>

                <dd class="rpcAddress" id="rpcAddrId">
                    @Html.DisplayFor(model => model.RpcAddr)
                </dd>

                <dt id="rpcPort">
                    @Html.DisplayNameFor(model => model.RpcPort)
                </dt>

                <dd class="rpcPort" id="rpcPortId">
                    @Html.DisplayFor(model => model.RpcPort)
                </dd>

                @switch (Model.Direction)
                {
                    case DirectionEnum.Source:
                        @foreach (var item in Model.Properties.First().SourceProperties)
                        {
                            <dt>
                                @Html.DisplayFor(model => item.Name)
                            </dt>

                            @if (item.PropertyType == PropertyTypeEnum.Password)
                            {
                                @Html.Raw("\u2022\u2022\u2022\u2022\u2022")
                            }
                            else
                            {
                                if (item.Value == String.Empty)
                                {
                                    <dd>
                                        &nbsp;
                                    </dd>
                                }
                                else
                                {
                                    <dd>
                                        @Html.DisplayFor(model => item.Value)
                                    </dd>
                                }
                            }
                        }

                        break;
                    case DirectionEnum.Destination:
                        @foreach (var item in Model.Properties.First().DestinationProperties)
                        {
                            <dt>
                                @Html.DisplayFor(model => item.Name)
                            </dt>

                            @if (item.PropertyType == PropertyTypeEnum.Password)
                            {
                                @Html.Raw("\u2022\u2022\u2022\u2022\u2022")
                            }
                            else
                            {
                                if (item.Value == String.Empty)
                                {
                                    <dd>
                                        &nbsp;
                                    </dd>
                                }
                                else
                                {
                                    <dd>
                                        @Html.DisplayFor(model => item.Value)
                                    </dd>
                                }
                            }
                        }
                        break;
                }

            </dl>

        </div>
        <div class="modal-footer">
            <div class="form-group col-md-12">
                <button type="button" class="btn btn-primary btn-sm" onclick="editCryptoAdapterFromDetails(@Model.Id)" title="Edit crypto adapter">
                    <i class="fa fa-edit fa-lg"></i> Edit
                </button>
                <button type="button" class="btn btn-primary btn-sm" onclick="closeCryptoAdapterModal()">Close</button>
            </div>
        </div>
    </div>
</div>

<script>

    function closeCryptoAdapterModal() {
        jQuery("#cryptoAdapterDetailsModal").modal("hide");
        jQuery("#cryptoAdapterDetailsContainer").html("");
    }

    //body class="modal-open" dissapear after closing cryptoAdapterDetailsModal (refactor!)
    function editCryptoAdapterFromDetails(Id) {
        closeCryptoAdapterModal();
        editCryptoAdapter(Id);
    }

</script>