Trunk/Prometheus.Web/Controllers/EnterpriseAdapterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prometheus.BL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Prometheus.Common.Extensiosns;
using Prometheus.Model.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Prometheus.Model.Models.EnterpriseAdapterModel;
using Prometheus.Common.Enums;

namespace Prometheus.Web.Controllers
{
    [Authorize]
    public class EnterpriseAdapterController : Controller
    {
        private readonly IEnterpriseAdapterService _enterpriseAdapterService;

        public EnterpriseAdapterController(IEnterpriseAdapterService enterpriseAdapterService)
        {
            _enterpriseAdapterService = enterpriseAdapterService;
        }


        public IActionResult Index()
        {
            var result = _enterpriseAdapterService.GetEnterpriseAdapters(User.Identity.GetUserProfileId() ?? default(long));

            if (result.Status != StatusEnum.Success)
            {
                return BadRequest();
            }
            return View(result.Value);
        }


        [HttpGet]
        public IActionResult Edit(long id)
        {
            var result = _enterpriseAdapterService.GetEnterpriseAdapter(id);
            if (result.Status == StatusEnum.Error)
            {
                return BadRequest();
            }
            return View(result.Value);

        }

        [HttpPost]
        public IActionResult Edit(EnterpriseAdapterModel model)
        {         
            if (ModelState.IsValid) {

                var result = _enterpriseAdapterService.UpdateEnterpriseAdapter(model);
                return Json(result);
            }
            return View(model);
        }


        public IActionResult Create()
        {
            var model = _enterpriseAdapterService.GetInitModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(EnterpriseAdapterModel model)
        {
            var userProfileId = User.Identity.GetUserProfileId();
            if (ModelState.IsValid)
            {
                var result = _enterpriseAdapterService.Create(model, (long)userProfileId);
                return Json(result);
            }
            return View(model);
        }


        [HttpPost]
        public IActionResult Delete(long enterpriseAdapterId)
        {
            var response = _enterpriseAdapterService.DeleteEnterpriseAdapter(enterpriseAdapterId);

            return Json(response);
        }

        [HttpGet]
        public IActionResult Details(long? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var result = _enterpriseAdapterService.GetEnterpriseAdapter(Convert.ToInt64(Id));

            return PartialView("_DetailsPartial", result.Value);
        }

        [HttpGet]
        public IActionResult CreateXML()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateXMLPost()
        {
            var userProfileId = User.Identity.GetUserProfileId();

            var fileUpload = Request.Form.Files;
            var file = fileUpload.GetFile(fileUpload[0].Name);

            var fileAsString = String.Empty;
            using (var reader = new StreamReader(file.OpenReadStream()))
            {
                fileAsString = reader.ReadToEnd();
            }

            if (string.IsNullOrEmpty(fileAsString) || userProfileId == null)
            {
                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            var response = _enterpriseAdapterService.CreateXML(fileAsString, (long)userProfileId);
            return Json(response);
        }
    }
}

Trunk/Prometheus.Web/Views/EnterpriseAdapter/CreateXML.cshtml
<div class="content mt-3">
    <div class="col-sm-12 mb-4">
        <h5>
            Create XML file for enterprise adapter, then upload it
        </h5>
    </div>

    <div class="col-sm-12">

        <form method="post" enctype="multipart/form-data">
            <input type="file" id="file" name="file" accept=".xml" />
            <br />
            <button type="button" class="btn btn-primary btn-sm mt-2" onclick="validate()">
                <i class="fa fa-upload"></i> Upload
            </button>
        </form>
    </div>

    <div class="col-md-12 mt-5" style="overflow-x:auto;">
        <div class="card">
            <div class="card-header" id="headingOne" style="background-color:#f1f2f7">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        XML Example
                    </button>
                </h5>
            </div>
            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">

                <code style="color:#4C0000;">

                    <pre>
    
   <b style="color:black">IF ENTERPRISE ADAPTER IS USED AS SOURCE (TO READ DATA FROM DATABASE):</b>

    &lt;prometheus&gt;
        &lt;adapter&gt;<b style="color:black">{MSSQL/MySQL/Oracle}</b>&lt;/adapter&gt;
        &lt;ipaddress&gt;<b style="color:black">{IP address of your server}</b>&lt;/ipaddress&gt;
        &lt;port&gt;<b style="color:black">{Port of your server}</b>&lt;/port&gt;
        &lt;database&gt;<b style="color:black">{Database name}</b>&lt;/database&gt;
        &lt;username&gt;<b style="color:black">{Username for that database}</b>&lt;/username&gt;
        &lt;password&gt;<b style="color:black">{Password for that database}</b>&lt;/password&gt;
        &lt;direction&gt;<b style="color:black">{Source}</b>&lt;/direction&gt;
        &lt;transactionTable&gt;
            &lt;tableName&gt;<b style="color:black">{Table name}</b>&lt;/name&gt;
            &lt;columns&gt;
                &lt;column property="<b style="color:black">{transactionId/transactionAccount/transactionAmount/transactionType}</b>" PK="<b style="color:black">{true/false}</b>" FK="false"&gt;<b style="color:black">{Column name}</b>&lt;/column&gt;
                &lt;column property="<b style="color:black">{transactionId/transactionAccount/transactionAmount/transactionType}</b>" PK="<b style="color:black">{true/false}</b>" FK="false"&gt;<b style="color:black">{Column name}</b>&lt;/column&gt;
                &lt;column property="<b style="color:black">{transactionId/transactionAccount/transactionAmount/transactionType}</b>" PK="<b style="color:black">{true/false}</b>" FK="false"&gt;<b style="color:black">{Column name}</b>&lt;/column&gt;
                &lt;column property="" PK="false" FK="true"&gt;
                    &lt;columnName&gt;<b style="color:black">{Column name}</b>&lt;/columnName&gt;
                    &lt;relatedTableName&gt;<b style="color:black">{Table name}</b>&lt;/relatedTableName&gt;
                    &lt;primaryKey property=""&gt;<b style="color:black">{Column name}</b>&lt;/primaryKey&gt;
                    &lt;descriptionColumn property="<b style="color:black">{transactionId/transactionAccount/TransactionAmount/TransactionType}</b>"&gt;<b style="color:black">{Column name}</b>&lt;/descriptionColumn&gt;
                &lt;/column&gt;
            &lt;/columns&gt;
        &lt;/transactionTable&gt;
    &lt;/prometheus&gt;


   <b style="color:black">IF ENTERPRISE ADAPTER IS USED AS DESTINATION (TO WRITE DATA INTO DATABASE):</b>

    &lt;prometheus&gt;
        &lt;adapter&gt;<b style="color:black">{MSSQL/MySQL/Oracle}</b>&lt;/adapter&gt;
        &lt;ipaddress&gt;<b style="color:black">{IP address of your server}</b>&lt;/ipaddress&gt;
        &lt;port&gt;<b style="color:black">{Port of your server}</b>&lt;/port&gt;
        &lt;database&gt;<b style="color:black">{Database name}</b>&lt;/database&gt;
        &lt;username&gt;<b style="color:black">{Username for that database}</b>&lt;/username&gt;
        &lt;password&gt;<b style="color:black">{Password for that database}</b>&lt;/password&gt;
        &lt;direction&gt;<b style="color:black">{Destination}</b>&lt;/direction&gt;
        &lt;tableNamePrefix&gt;<b style="color:black">{Prefix you want to see in front of table names that we create}</b>&lt;/tableNamePrefix&gt;
    &lt;/prometheus&gt;
</pre>

                </code>

            </div>
        </div>
    </div>
</div>


@section Scripts{


    <script>

    jQuery(document).ready(function () {

        jQuery("#example").click(function () {
            jQuery("#xmlExample").toggle();
        });
    });

    function validate() {

        var file = jQuery("#file").get(0).files;

        if (file.length == 0) {
            bootbox.alert("Please select a file to upload.")
        }
        else {
            var fileName = file[0].name;
            var fileExtension = fileName.split('.').pop();

            if (fileExtension != "xml") {
                bootbox.alert("Please upload .xml files only.");
            }
            else {
                load(file);
            }
        }
    }

    function load(file) {

        var data = new FormData();
        data.append(file[0].name, file[0]);

        var dialog = bootbox.dialog({
            message: '<div class="text-center"><i class="fa fa-spin fa-spinner"></i> Loading ...</div>',
            closeButton: false
        })

        setTimeout(function () {
            jQuery.ajax({
                type: "POST",
                url: '@Url.Action("CreateXMLPost", "EnterpriseAdapter")',
                contentType: false,
                processData: false,
                data: data,
                success: function (response) {
                    dialog.modal('hide');

                    bootbox.alert(response.message, function () {
                        dialog.modal('hide');

                        if (response.status == 0) {
                            window.location.replace('@Url.Action("Index", "EnterpriseAdapter")')
                        }
                    })
                },
                error: function () {
                    dialog.modal('hide');
                    bootbox.alert("There was a problem uploading the file. Check the data you entered.", function () {
                        dialog.modal('hide');
                    })
                }
            })
        }, 500)
    }

    </script>

}

Trunk/Prometheus.Web/Views/EnterpriseAdapter/Index.cshtml
@using Prometheus.Model.Models.EnterpriseAdapterModel

@model IEnumerable<EnterpriseAdapterModel>
@{
    int counter = 0;
}

@section Styles{

    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
}

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">

            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title">Enterprise Adapter</strong>
                        <a asp-controller="EnterpriseAdapter" asp-action="Create" title="Add enterprise adapter (Form)"> &nbsp;<i class="fa fa-plus-square-o fa-lg"></i></a>
                        <a asp-controller="EnterpriseAdapter" asp-action="CreateXML" title="Add enterprise adapter (XML)"> &nbsp;<i class="fa fa-file-code-o"></i></a>
                    </div>
                    <div class="card-body">
                        <div style="overflow-x:auto;">
                            <table id="enterpriseAdaptersTable" class="table table-striped table-bordered">
                                <thead>
                                    <tr role="row">
                                        <th style="text-align:center">#</th>
                                        <th>Name</th>
                                        <th>Adapter Type</th>
                                        <th>Direction</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr role="row" class="odd">
                                            <td class="sorting_1" style="text-align:center">@(counter += 1)</td>
                                            <td>
                                                <a href="#" onclick="enterpriseAdapterDetails(@item.Id)" title="Details">
                                                    @item.Name
                                                </a>
                                            </td>
                                            <td>@item.EnterpriseAdapter</td>
                                            <td>@item.Direction.ToString()</td>
                                            <td>
                                                <a href="#" onclick="enterpriseAdapterDetails(@item.Id)" title="Details">
                                                    <i class="fa fa-info-circle fa-lg"></i>
                                                </a>
                                                &nbsp;
                                                <a href="@Url.Action("Edit", "EnterpriseAdapter", new { id = item.Id })" title="Edit">
                                                    <i class="fa fa-pencil fa-lg"></i>
                                                </a>
                                                &nbsp;
                                                <a href="#" onclick="confirmDelete(@item.Id)" title="Delete">
                                                    <i class="fa fa-trash fa-lg"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div><!-- .animated -->
</div>


<div class="modal fade" id="enterpriseAdapterDetailsModal" tabindex="-1" role="dialog" aria-labelledby="enterpriseAdapterDetailsModal" aria-hidden="true" data-backdrop="static">
    <div id="enterpriseAdapterDetailsContainer">
    </div>
</div>


@section Scripts{

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>

    <script>
        jQuery(document).ready(function () {
            jQuery("#enterpriseAdaptersTable").dataTable({
                "ordering": false
            });
        });

        function confirmDelete(entAdapterId) {

            var confirmedBootbox = bootbox.confirm("Are you sure you want to delete this enterprise adapter?", function (result) {

                if (result) {

                    var id = entAdapterId;

                    jQuery.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "EnterpriseAdapter")',
                        data: { enterpriseAdapterId: id },
                        dataType: 'json',
                        success: function (response) {
                            if (response.message != null) {

                                bootbox.alert(response.message);
                            }
                            else {
                                window.location.replace('@Url.Action("Index", "EnterpriseAdapter")');
                            }
                        },
                        error: function () {
                            bootbox.alert("Something went wrong. Please try again later.")
                        }
                    });
                }
            })
        }

        function enterpriseAdapterDetails(Id) {

            jQuery.ajax({
                type: "GET",
                url: '@Url.Action("Details", "EnterpriseAdapter")',
                data: { Id: Id },
                success: function (model) {

                    jQuery('#enterpriseAdapterDetailsContainer').html(model);
                    jQuery('#enterpriseAdapterDetailsModal').modal("show");
                }
            });
        };

    </script>
}

Trunk/Prometheus.Web/Views/EnterpriseAdapter/_DetailsPartial.cshtml
@using Prometheus.Model.Models.EnterpriseAdapterModel

@model EnterpriseAdapterModel

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Enterprise Adapter Details</h4>
            <button type="button" class="close" onclick="closeEnterpriseAdapterModal()">&times;</button>
        </div>

        <div class="modal-body">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.EnterpriseAdapter)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EnterpriseAdapter)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ServerIP)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ServerIP)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Port)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Port)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Username)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Username)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Password)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Password)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DatabaseName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.DatabaseName)
                </dd>

                @switch (Model.Direction)
                {
                    case DirectionEnum.Source:
                        if (Model.ParentTable != null)
                        {
                            <dt>
                                @Html.DisplayNameFor(model => model.ParentTable)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.ParentTable)
                            </dd>
                        }
                        @foreach (var item in Model.Properties.First().SourceProperties)
                        {
                            <dt>
                                @Html.DisplayFor(model => item.Name)
                            </dt>

                            if (item.Value == String.Empty)
                            {
                                <dd>
                                    &nbsp;
                                </dd>
                            }
                            else
                            {
                                <dd>
                                    @Html.DisplayFor(model => item.Value)
                                </dd>
                            }
                        }

                        break;
                    case DirectionEnum.Destination:
                        @foreach (var item in Model.Properties.First().DestinationProperties)
                        {
                            <dt>
                                @Html.DisplayFor(model => item.Name)
                            </dt>

                            if (item.Value == String.Empty)
                            {
                                <dd>
                                    &nbsp;
                                </dd>
                            }
                            else
                            {
                                <dd>
                                    @Html.DisplayFor(model => item.Value)
                                </dd>
                            }
                        }
                        break;
                }

            </dl>

        </div>
        <div class="modal-footer">
            <div class="form-group col-md-12">
                <a class="btn btn-primary btn-sm" href="@Url.Action("Edit", "EnterpriseAdapter", new { id = Model.Id })">
                    <i class="fa fa-edit fa-lg"></i> Edit
                </a>
                <button type="button" class="btn btn-primary btn-sm" onclick="closeEnterpriseAdapterModal()">Close</button>
            </div>
        </div>
    </div>
</div>

<script>

    function closeEnterpriseAdapterModal() {
        jQuery("#enterpriseAdapterDetailsModal").modal("hide");
        jQuery("#enterpriseAdapterDetailsContainer").html("");
    }

</script>